export interface ITypesIvaFee {
  label: string
  code: string
  declarationCode: number
  fee: number
  status: boolean
}
export interface ICodeRetention {
  code: string
  code_303: number
  name: string
  description: string
  fee: string
  resolution?: string
}
export const typesIvaFee: ITypesIvaFee[] = [
  { label: '0%', code: '0', declarationCode: 507, fee: 0, status: true },
  { label: '12%', code: '2', declarationCode: 500, fee: 12, status: false },
  { label: '14%', code: '3', declarationCode: 500, fee: 14, status: false },
  { label: 'No Objeto de Impuesto', code: '6', declarationCode: 532, fee: 0, status: true },
  { label: 'Exento de IVA', code: '7', declarationCode: 532, fee: 0, status: true },
  { label: '13%', code: '10', declarationCode: 500, fee: 13, status: false },
  { label: '15%', code: '4', declarationCode: 500, fee: 15, status: true },
  { label: '5%', code: '5', declarationCode: 540, fee: 5, status: true },
  { label: 'Iva Diferenciado', code: '8', declarationCode: 500, fee: 5, status: false },
]

export const typeRtFee = [
  { value: '2', code: '1', label: 'I_Renta' },
  { value: '1', code: '2', label: 'IVA' },
  { value: '3', code: '6', label: 'ISD' },
]

export const typeDocument = [
  { value: '01', label: 'FACTURA', shortName: 'FAC' },
  { value: '03', label: 'LIQUIDACIÓN DE COMPRA DE BIENES Y PRESTACIÓN DE SERVICIOS', shortName: 'LIQ' },
  { value: '04', label: 'NOTA DE CRÉDITO', shortName: 'NC' },
  { value: '05', label: 'NOTA DE DÉBITO', shortName: 'ND' },
  { value: '06', label: 'GUÍA DE REMISIÓN', shortName: 'GR' },
  { value: '07', label: 'RETENCIÓN', shortName: 'RET' },
]

export const TYPE_IDENTITY = [
  { label: 'RUC', value: '04', forForm: true },
  { label: 'Cédula', value: '05', forForm: true },
  { label: 'Pasaporte', value: '06', forForm: true },
  { label: 'Consumidor Final', value: '07' },
  { label: 'Identificación del Exterior', value: '08', forForm: true },
  { label: 'Placa', value: '09' },
]

export const typesPaymentSRI = [
  { value: '01', label: 'SIN UTILIZACIÓN DEL SISTEMA FINANCIERO' },
  { value: '15', label: 'COMPENSACIÓN DE DEUDAS' },
  { value: '16', label: 'TARJETA DE DÉBITO' },
  { value: '17', label: 'DINERO ELECTRÓNICO' },
  { value: '18', label: 'TARJETA PREPAGO' },
  { value: '19', label: 'TARJETA DE CRÉDITO' },
  { value: '20', label: 'OTROS CON UTILIZACIÓN DEL SISTEMA FINANCIERO' },
  { value: '21', label: 'ENDOSO DE TÍTULOS' },
]

export const codesPercentageIVA: ICodeRetention[] = [
  {
    code: '7',
    name: 'Retención de iva 0%',
    description: 'Aplica de conformidad con la Disposición Transitoria Única de la Resolución NAC-DGERCGC15-00000284',
    fee: '0',
    code_303: 7,
  },
  {
    code: '8',
    name: 'No aplica Retención IVA',
    description: 'No aplica Retención IVA',
    fee: '0',
    code_303: 8,
  },

  {
    code: '1',
    name: 'Retención de iva 30%',
    description: 'Se suele usar para Bienes o contratos de contracción para Empresas O Persona NATURAL',
    fee: '30',
    code_303: 1,
  },
  {
    code: '2',
    name: 'Retención de iva 70%',
    description: 'Se suele usar para Servicios en Empresas O Persona NATURAL',
    fee: '70',
    code_303: 2,
  },
  {
    code: '3',
    name: 'Retención de iva 100%',
    description: 'Se usa para HONORARIOS PROFESIONALES y arriendo de inmuebles',
    fee: '100',
    code_303: 3,
  },
  {
    code: '9',
    name: 'Retención de iva 10%',
    description: 'Suele usar para compra de BIENES por parte de un Contribuyente Especial',
    fee: '10',
    code_303: 9,
  },
  {
    code: '10',
    name: 'Retención de iva 20%',
    description: 'Suele usar para compra de SERVICIOS por parte de un Contribuyente Especial',
    fee: '20',
    code_303: 10,
  },

]

export const codesPercentageIR: ICodeRetention[] = [
  {
    name: 'Honorarios profesionales',
    description: 'Honorarios profesionales y demás pagos por servicios relacionados con el título profesional',
    fee: '10',
    code_303: 303,
    code: '303',
  },
  {
    name: 'Servicios profesionales residentes',
    description: 'Servicios profesionales prestados por sociedades residentes',
    fee: '5',
    code_303: 3030,
    code: '303A',
    resolution: 'NAC-DGERCGC26-9',
  },
  {
    name: 'Servicios intelectuales no relacionados',
    description: 'Servicios predomina el intelecto no relacionados con el título profesional',
    fee: '10',
    code_303: 304,
    code: '304',
  },
  {
    name: 'Comisiones servicios intelectuales no relacionados',
    description: 'Comisiones y demás pagos por servicios predomina intelecto no relacionados con el título profesional',
    fee: '10',
    code_303: 304,
    code: '304A',
  },
  {
    name: 'Pagos a notarios y registradores',
    description: 'Pagos a notarios y registradores de la propiedad y mercantil por sus actividades ejercidas como tales',
    fee: '10',
    code_303: 304,
    code: '304B',
  },
  {
    name: 'Pagos a deportistas y técnicos',
    description: 'Pagos a deportistas, entrenadores, árbitros, miembros del cuerpo técnico por sus actividades ejercidas como tales',
    fee: '10',
    code_303: 304,
    code: '304C',
    resolution: 'NAC-DGERCGC26-9',
  },
  {
    name: 'Pagos a artistas',
    description: 'Pagos a artistas por sus actividades ejercidas como tales',
    fee: '10',
    code_303: 304,
    code: '304D',
    resolution: 'NAC-DGERCGC26-9',
  },
  {
    name: 'Honorarios por servicios de docencia',
    description: 'Honorarios y demás pagos por servicios de docencia',
    fee: '10',
    code_303: 304,
    code: '304E',
  },
  {
    name: 'Servicios predominan mano de obra',
    description: 'Servicios predomina la mano de obra',
    fee: '3',
    code_303: 307,
    code: '307',
    resolution: 'NAC-DGERCGC26-9',
  },
  {
    name: 'Uso de imagen o renombre',
    description: 'Utilización o aprovechamiento de la imagen o renombre (personas naturales, sociedades," influencers")',
    fee: '10',
    code_303: 308,
    code: '308',
  },
  {
    name: 'Servicios de medios y publicidad',
    description: 'Servicios prestados por medios de comunicación y agencias de publicidad',
    fee: '3',
    code_303: 309,
    code: '309',
    resolution: 'NAC-DGERCGC26-9',
  },
  {
    name: 'Transporte privado y público',
    description: 'Servicio de transporte privado de pasajeros o transporte público o privado de carga',
    fee: '1',
    code_303: 310,
    code: '310',
  },
  {
    name: 'Pagos por liquidación de compra',
    description: 'Pagos a través de liquidación de compra (nivel cultural o rusticidad)',
    fee: '3',
    code_303: 311,
    code: '311',
    resolution: 'NAC-DGERCGC26-9',
  },
  {
    name: 'Transferencia bienes muebles',
    description: 'Transferencia de bienes muebles de naturaleza corporal',
    fee: '2',
    code_303: 312,
    code: '312',
    resolution: 'NAC-DGERCGC26-9',
  },
  {
    name: 'Compras al productor bioacuáticos y forestales',
    description: 'COMPRAS AL PRODUCTOR: de bienes de origen bioacuático, forestal y los descritos  el art.27.1 de LRTI',
    fee: '1',
    code_303: 3120,
    code: '312A',
  },
  {
    name: 'Compras al comercializador bioacuáticos y forestales',
    description: 'COMPRAS AL COMERCIALIZADOR: de bienes de origen bioacuático, forestal y los descritos  el art.27.1 de LRTI',
    fee: '1.75',
    code_303: 3121,
    code: '312C',
  },
  {
    name: 'Regalías por franquicias personas naturales',
    description: 'Regalías por concepto de franquicias de acuerdo al Código INGENIOS (COESCCI) - pago a personas naturales',
    fee: '10',
    code_303: 314,
    code: '314A',
  },
  {
    name: 'Cánones y derechos de autor personas naturales',
    description: 'Cánones, derechos de autor,  marcas, patentes y similares de acuerdo  al Código INGENIOS (COESCCI) – pago a personas naturales',
    fee: '10',
    code_303: 314,
    code: '314B',
  },
  {
    name: 'Regalías por franquicias sociedades',
    description: 'Regalías por concepto de franquicias de acuerdo al Código INGENIOS (COESCCI) - pago a sociades',
    fee: '10',
    code_303: 314,
    code: '314C',
  },
  {
    name: 'Cánones y derechos de autor sociedades',
    description: 'Cánones, derechos de autor,  marcas, patentes y similares de acuerdo  al Código INGENIOS (COESCCI)',
    fee: '10',
    code_303: 314,
    code: '314D',
  },
  {
    name: 'Cuotas arrendamiento mercantil',
    description: 'Cuotas de arrendamiento mercantil (prestado por sociedades), inclusive la de opción de compra',
    fee: '2',
    code_303: 319,
    code: '319',
  },
  {
    name: 'Arrendamiento bienes inmuebles',
    description: 'Arrendamiento bienes inmuebles',
    fee: '10',
    code_303: 320,
    code: '320',
  },
  {
    name: 'Seguros y reaseguros',
    description: 'Seguros y reaseguros (primas y cesiones)',
    fee: '2',
    code_303: 322,
    code: '322',
    resolution: 'NAC-DGERCGC26-9',
  },
  {
    name: 'Rendimientos financieros naturales y sociedades',
    description: 'Rendimientos financieros pagados a naturales y sociedades  (No a IFIs)',
    fee: '2',
    code_303: 323,
    code: '323',
  },
  {
    name: 'Rendimientos financieros depósitos Cta. Corriente',
    description: 'Rendimientos financieros: depósitos Cta. Corriente',
    fee: '2',
    code_303: 323,
    code: '323A',
  },
  {
    name: 'Rendimientos financieros depósitos Cta. Ahorros Sociedades',
    description: 'Rendimientos financieros:  depósitos Cta. Ahorros Sociedades',
    fee: '2',
    code_303: 323,
    code: '323B1',
  },
  {
    name: 'Rendimientos financieros depósito a plazo fijo gravados',
    description: 'Rendimientos financieros: depósito a plazo fijo  gravados',
    fee: '2',
    code_303: 323,
    code: '323E',
  },
  {
    name: 'Rendimientos financieros depósito a plazo fijo exentos',
    description: 'Rendimientos financieros: depósito a plazo fijo exentos',
    fee: '0',
    code_303: 332,
    code: '32300',
  },
  {
    name: 'Rendimientos financieros operaciones de reporto',
    description: 'Rendimientos financieros: operaciones de reporto - repos',
    fee: '2',
    code_303: 323,
    code: '323F',
  },
  {
    name: 'Inversiones rendimientos distintos a IFIs',
    description: 'Inversiones (captaciones) rendimientos distintos de aquellos pagados a IFIs',
    fee: '2',
    code_303: 323,
    code: '323G',
  },
  {
    name: 'Rendimientos financieros obligaciones',
    description: 'Rendimientos financieros: obligaciones',
    fee: '2',
    code_303: 323,
    code: '323H',
  },
  {
    name: 'Rendimientos financieros bonos convertibles',
    description: 'Rendimientos financieros: bonos convertible en acciones',
    fee: '2',
    code_303: 323,
    code: '323I',
  },
  {
    name: 'Rendimientos financieros títulos valores renta fija gravados',
    description: 'Rendimientos financieros: Inversiones en títulos valores en renta fija gravados',
    fee: '2',
    code_303: 323,
    code: '323 M',
  },
  {
    name: 'Rendimientos financieros títulos valores renta fija exentos',
    description: 'Rendimientos financieros: Inversiones en títulos valores en renta fija exentos',
    fee: '0',
    code_303: 332,
    code: '323 N',
  },
  {
    name: 'Intereses pagados por entidades bancarias',
    description: 'Intereses y demás rendimientos financieros pagados a bancos y otras entidades sometidas al control de la Superintendencia de Bancos y de la Economía Popular y Solidaria',
    fee: '0',
    code_303: 332,
    code: '323 O',
  },
  {
    name: 'Intereses pagos sector público',
    description: 'Intereses pagados por entidades del sector público a favor de sujetos pasivos',
    fee: '2',
    code_303: 323,
    code: '323 P',
  },
  {
    name: 'Otros intereses y rendimientos gravados',
    description: 'Otros intereses y rendimientos financieros gravados',
    fee: '2',
    code_303: 323,
    code: '323Q',
  },
  {
    name: 'Otros intereses y rendimientos exentos',
    description: 'Otros intereses y rendimientos financieros exentos',
    fee: '0',
    code_303: 332,
    code: '323R',
  },
  {
    name: 'Pagos BCE a instituciones financieras',
    description: 'Pagos y créditos en cuenta efectuados por el BCE y los depósitos centralizados de valores, en calidad de intermediarios, a instituciones del sistema financiero por cuenta de otras personas naturales y sociedades',
    fee: '2',
    code_303: 323,
    code: '323S',
  },
  {
    name: 'Rendimientos deuda pública ecuatoriana',
    description: 'Rendimientos financieros originados en la deuda pública ecuatoriana',
    fee: '0',
    code_303: 332,
    code: '323T',
  },
  {
    name: 'Rendimientos títulos valores proyectos públicos',
    description: 'Rendimientos financieros originados en títulos valores de obligaciones de 360 días o más para el financiamiento de proyectos públicos en asociación público-privada',
    fee: '0',
    code_303: 332,
    code: '323U',
  },
  {
    name: 'Intereses y comisiones crédito entre instituciones financieras',
    description: 'Intereses y comisiones en operaciones de crédito entre instituciones del sistema financiero y entidades economía popular y solidaria.',
    fee: '1',
    code_303: 324,
    code: '324A',
  },
  {
    name: 'Inversiones entre instituciones financieras',
    description: 'Inversiones entre instituciones del sistema financiero y entidades economía popular y solidaria',
    fee: '1',
    code_303: 324,
    code: '324B',
  },
  {
    name: 'Pagos BCE a instituciones financieras por cuenta de otras',
    description: 'Pagos y créditos en cuenta efectuados por el BCE y los depósitos centralizados de valores, en calidad de intermediarios, a instituciones del sistema financiero por cuenta de otras instituciones del sistema financiero',
    fee: '1',
    code_303: 324,
    code: '324C',
  },
  {
    name: 'Anticipo dividendos',
    description: 'Anticipo dividendos',
    fee: '22',
    code_303: 325,
    code: '325',
  },
  {
    name: 'Préstamos accionistas residentes',
    description: 'Préstamos accionistas, beneficiarios o partícipes residentes o establecidos en el Ecuador',
    fee: '22',
    code_303: 325,
    code: '325A',
  },
  {
    name: 'Dividendos impuestos a la renta único',
    description: 'Dividendos distribuidos que correspondan al impuesto a la renta único establecido en el art. 27 de la LRTI',
    fee: '25',
    code_303: 326,
    code: '326',
  },
  {
    name: 'Dividendos a personas naturales residentes',
    description: 'Dividendos distribuidos a personas naturales residentes',
    fee: '25',
    code_303: 327,
    code: '327',
  },
  {
    name: 'Dividendos a sociedades residentes',
    description: 'Dividendos distribuidos a sociedades residentes',
    fee: '0',
    code_303: 328,
    code: '328',
  },
  {
    name: 'Dividendos a fideicomisos residentes',
    description: 'Dividendos distribuidos a fideicomisos residentes',
    fee: '0',
    code_303: 329,
    code: '329',
  },
  {
    name: 'Dividendos en acciones',
    description: 'Dividendos en acciones (capitalización de utilidades)',
    fee: '0',
    code_303: 331,
    code: '331',
  },
  {
    name: 'Otras compras bienes y servicios no sujetos a retención',
    description: 'Otras compras de bienes y servicios no sujetas a retención (incluye régimen RIMPE - Negocios Populares para este caso aplica con cualquier forma de pago inclusive los pagos que deban realizar las tarjetas de crédito/débito)',
    fee: '0',
    code_303: 332,
    code: '332',
  },
  {
    name: 'Compra de bienes inmuebles',
    description: 'Compra de bienes inmuebles',
    fee: '0',
    code_303: 332,
    code: '332B',
  },
  {
    name: 'Transporte público de pasajeros',
    description: 'Transporte público de pasajeros',
    fee: '0',
    code_303: 332,
    code: '332C',
  },
  {
    name: 'Pagos transporte internacional de carga',
    description: 'Pagos en el país por transporte de pasajeros o transporte internacional de carga, a compañías nacionales o extranjeras de aviación o marítimas',
    fee: '0',
    code_303: 332,
    code: '332D',
  },
  {
    name: 'Valores cooperativas transporte',
    description: 'Valores entregados por las cooperativas de transporte a sus socios',
    fee: '0',
    code_303: 332,
    code: '332E',
  },
  {
    name: 'Compraventa divisas no USD',
    description: 'Compraventa de divisas distintas al dólar de los Estados Unidos de América',
    fee: '0',
    code_303: 332,
    code: '332F',
  },
  {
    name: 'Pagos con tarjeta de crédito',
    description: 'Pagos con tarjeta de crédito',
    fee: '0',
    code_303: 332,
    code: '332G',
  },
  {
    name: 'Pago exterior tarjeta de crédito',
    description: 'Pago al exterior tarjeta de crédito reportada por la Emisora de tarjeta de crédito, solo RECAP',
    fee: '0',
    code_303: 332,
    code: '332H',
  },
  {
    name: 'Pago a través convenio débito',
    description: 'Pago a través de convenio de debito (Clientes IFI`s)',
    fee: '0',
    code_303: 332,
    code: '332I',
  },
  {
    name: 'Ganancia en enajenación de derechos',
    description: 'Ganancia en la enajenación de derechos representativos de capital u otros derechos que permitan la exploración, explotación, concesión o similares de sociedades, que se coticen en bolsa de valores del Ecuador',
    fee: '10',
    code_303: 333,
    code: '333',
  },
  {
    name: 'Contraprestación por enajenación de derechos no cotizados',
    description: 'Contraprestación producida por la enajenación de derechos representativos de capital u otros derechos que permitan la exploración, explotación, concesión o similares de sociedades, no cotizados en bolsa de valores del Ecuador',
    fee: '1',
    code_303: 334,
    code: '334',
  },
  {
    name: 'Loterías y apuestas',
    description: 'Loterías, rifas, pronosticos deportivos, apuestas y similares',
    fee: '15',
    code_303: 335,
    code: '335',
  },
  {
    name: 'Producción y venta local banano',
    description: 'Producción y venta local de banano producido o no por el mismo sujeto pasivo',
    fee: '1,2',
    code_303: 3380,
    code: '338',
  },
  {
    name: 'Impuesto único exportación banano',
    description: 'Impuesto único a la exportación de banano',
    fee: '3',
    code_303: 3400,
    code: '340',
  },
  {
    name: 'Otras retenciones 1%',
    description: 'Otras retenciones aplicables el 1% (incluye régimen RIMPE - Emprendedores, para este caso aplica con cualquier forma de pago inclusive los pagos que deban realizar las tarjetas de crédito/débito)',
    fee: '1',
    code_303: 343,
    code: '343',
  },
  {
    name: 'Energía eléctrica',
    description: 'Energía eléctrica',
    fee: '2',
    code_303: 343,
    code: '343A',
    resolution: 'NAC-DGERCGC26-9',
  },
  {
    name: 'Actividades de construcción y urbanización',
    description: 'Actividades de construcción de obra material inmueble, urbanización, lotización o actividades similares',
    fee: '2',
    code_303: 346,
    code: '343B',
    resolution: 'NAC-DGERCGC26-9',
  },
  {
    name: 'Recepción botellas plásticas no retornables',
    description: 'Recepción de botellas plásticas no retornables de PET',
    fee: '2',
    code_303: 343,
    code: '343C',
  },
  {
    name: 'Otras retenciones 3%',
    description: 'Otras retenciones aplicables el 3%',
    fee: '3',
    code_303: 3440,
    code: '3440',
    resolution: 'NAC-DGERCGC26-9',
  },
  {
    name: 'Pago local tarjeta de crédito/débito',
    description: 'Pago local tarjeta de crédito /débito reportada por la Emisora de tarjeta de crédito / entidades del sistema financiero',
    fee: '2',
    code_303: 344,
    code: '344A',
  },
  {
    name: 'Adquisición de sustancias minerales',
    description: 'Adquisición de sustancias minerales dentro del territorio nacional',
    fee: '2',
    code_303: 344,
    code: '344B',
  },
  {
    name: 'Otras retenciones 8%',
    description: 'Otras retenciones aplicables el 8%',
    fee: '8',
    code_303: 345,
    code: '345',
  },
  {
    name: 'Otras retenciones otros porcentajes',
    description: 'Otras retenciones aplicables a otros porcentajes',
    fee: '0',
    code_303: 346,
    code: '346',
  },
  {
    name: 'Otras ganancias de capital',
    description: 'Otras ganancias de capital distintas de enajenación de derechos representativos de capital',
    fee: '0',
    code_303: 346,
    code: '346A',
  },
  {
    name: 'Donaciones en dinero',
    description: 'Donaciones en dinero -Impuesto a la donaciones',
    fee: '0',
    code_303: 346,
    code: '346B',
  },
  {
    name: 'Retención por exportación de concentrados metálicos',
    description: 'Retención a cargo del propio sujeto pasivo por la exportación de concentrados y/o elementos metálicos',
    fee: '0,10',
    code_303: 346,
    code: '346C',
  },
  {
    name: 'Retención comercialización productos forestales',
    description: 'Retención a cargo del propio sujeto pasivo por la comercialización de productos forestales',
    fee: '0,10',
    code_303: 346,
    code: '346D',
  },
  {
    name: 'Impuesto único actividades agropecuarias',
    description: 'Impuesto único a ingresos provenientes de actividades agropecuarias en etapa de producción / comercialización local o exportación',
    fee: '1',
    code_303: 348,
    code: '348',
  },
  {
    name: 'Impuesto a operadores pronósticos deportivos',
    description: 'Impuesto a la renta único sobre los ingresos percibidos por los operadores de pronósticos deportivos (vigente desde 01/07/2024)',
    fee: '15',
    code_303: 3480,
    code: '3480',
  },
  {
    name: 'Comisiones a sociedades residentes y extranjeras',
    description: 'Comisiones  a sociedades, nacionales o extranjeras residentes y establecimientos permanentes domiciliados en el país',
    fee: '5',
    code_303: 3140,
    code: '3482',
    resolution: 'NAC-DGERCGC26-9',
  },
  {
    name: 'Otras autorretenciones',
    description: 'Otras autorretenciones (inciso 1 y 2 Art.92.1 RLRTI)',
    fee: '1.50,1.75',
    code_303: 350,
    code: '350',
  },
]
